### ISSUE TITLE
LTI compatibility problem

### ISSUE THREAD

**Issue by dcadiou** [moodleuulm/moodle-theme_boost_campus#120]
Hi.

LTI links fails if the Moodle acting as LTI provider is using the present theme and if `... | favicon` setting is set.

In such situation an error message appears, `Exception : Call to a member function out() on string`, on the LTI client, each time a new 'external tool' activity is added in a course, set to be linked with the failing provider.

This problem has already been discussed, for others themes, in https://tracker.moodle.org/browse/MDL-66272 (especially by Gareth J Barnard who explained the failure). It is linked to a solved Moodle core tracker : https://tracker.moodle.org/browse/MDL-66272.

However, despite tracker resolution for core, it still exists with the present theme.

The boost_campus function `favicon()` (in `classes/output/core_renderer.php`), calls `$this->page->theme->setting_file_url()` which returns a string, but `favicon()` function is supposed to return a `moodle_url` object (as `image_url()` does), not a string !

LTI plugin, line 102 of `enrol/lti/classes/tool_provider.php` is calling `$icon = helper::get_icon($tool)->out();`, which calls the `favicon()` function, but a string doesn't contains any `out()` function. This leads to the already mentioned error message.

Until this issue is resolved, we will need to remove any favicon settings on our platform for LTI to work.

**Comment by abias** [comment]
Hi @dcadiou ,

many thanks for creating this issue which remained unhandled up to now, unfortunately.

I had a look at MDL-66272 and have a adapted the boost_campus function `favicon()` in https://github.com/moodle-an-hochschulen/moodle-theme_boost_campus/commit/ea2f0509d692441c8bda15b6cf60cce84c8e9d32 to how it is built in Moodle 4.1dev core (where the custom favicon is introduced into the Moodle core). New releases will be pushed to moodle.org soon so that this LTI issue should be solved then.

Cheers,
Alex
