### ISSUE TITLE
Externe Einbettung von z.B. Opencast Videos im Kacheldesign oder in H5P-Videos bei Shibboleth-Authentifizierung

### ISSUE THREAD

**Issue by julialeede** [moodleuulm/moodle-theme_boost_campus#122]
Problem: Hochschulinterne Opencast Videos die als Externe Inhalte z.B. im Kacheldesign oder in H5P interaktive Videos in Moodle eingebettet werden, können nicht in Moodle abgespielt werden, wenn Shibboleth als Authentifizierung genutzt wird.

**Comment by abias** [comment]
Hi @julialeede ,

many thanks for creating this issue which remained unhandled up to now, unfortunately.

As we have documented on https://moodle.org/plugins/theme_boost_campus, Boost Campus will not be continued after Moodle 3.x anymore as we will focus on the successor Boost Union which is published on https://moodle.org/plugins/theme_boost_union. For the time being, as long as Moodle 3.x still receives security support, we will only fix critical bugs in Boost Campus if one arises.

The issue which you have raised here _could_ be a major bug, but I am unsure if it is a bug of Boost Campus at all.

I would like to ask you to check if this problem happens already when you use the Boost theme from Moodle core (instead of Boost Union).

If it really happens with Boost Union and not with Boost core, then please provide detailed steps to reproduce (see https://docs.moodle.org/400/en/How_to_add_steps_to_reproduce_to_a_bug_report#Example_of_test_steps for an example).

Cheers,
Alex

**Comment by abias** [comment]
As there wasn't any reply anymore, I will close this issue now.
Please do not hesitate to comment here again in case you are sure that this is a Boost campus issue.
