### ISSUE TITLE
Text hardly recognizable when inverting the default light navbar

### ISSUE THREAD

**Issue by ramonare** [moodleuulm/moodle-theme_boost_campus#20]
When inverting the default light navbar to a dark one some texts stay black/dark blue and are therefore hardly recognizable (e.g. text of language dropdown and links (hover effect)). 
I changed the navbar using the „dark navbar“ checkbox in the “design setting” tab. 
Moodle 3.4.1, Boost Campus v3.4-r1 (version: 2018021900).

![links on hover hardly recognizable](https://user-images.githubusercontent.com/36665700/36476039-fc84af86-16fc-11e8-9360-c1cfb159e601.png)

![change language hardly recognizable](https://user-images.githubusercontent.com/36665700/36476040-fca1a140-16fc-11e8-9494-190312ba0a41.png)

**Comment by Kathrin84** [comment]
Hi ramonare,

thank you for reporting this issue. After publishing the first 3.4 release, I also saw that the language switcher is not yet white. I had only installed English so far and therefore it did not appeared.
In the next release it will be set to white.

Regarding you hovering question: 
This is only hardly recognisable in your instance because you have a pretty dark brand color, wich is used as the hovering color.

I hesitate to disable the hovering in the darf navbar entirely because other brand colors would work fine. If you need to change this behaviour just add corresponding CSS rules in the setting "theme_boost_campus | scss". There you can define your own hovering design.

Best, Kathrin
