### ISSUE TITLE
Text and icons of footer blocks unreadable

### ISSUE THREAD

**Issue by t-schroeder** [moodleuulm/moodle-theme_boost_campus#21]
When placing a block in the footer, its text and icons become white which makes them invisible on the white background of the block.

You can remedy this with custom CSS but it would be nice if the theme would already take care of it.

![unbenannt](https://user-images.githubusercontent.com/24255259/36782792-5d961c2e-1c7a-11e8-991c-2addb767c177.PNG)
![unbenannt2](https://user-images.githubusercontent.com/24255259/36783407-2f9d5394-1c7c-11e8-9d5a-e91ed5a2f285.PNG)
![unbenannt3](https://user-images.githubusercontent.com/24255259/36783412-344203d6-1c7c-11e8-86b0-e68e20ba6f53.png)
![unbenannt4](https://user-images.githubusercontent.com/24255259/36783416-3604e940-1c7c-11e8-972a-73d2c1df3d60.png)

**Comment by Kathrin84** [comment]
Hi do-you-even-curl,
thanks for the issue. 
We've already discovered this and fixed it with this commit:
https://github.com/moodleuulm/moodle-theme_boost_campus/commit/f042b5e6d161145dad702d82e00336771a5ac03e
It is part of the release version 3.4-r2. Do you use this version already?
Best, Kathrin

**Comment by t-schroeder** [comment]
Hi Kathrin,
my bad. I was using 3.4-r1 on that Moodle instance. Now that I've upgraded to 3.4-3 it looks like this:
![unbenannt2](https://user-images.githubusercontent.com/24255259/36794827-b8b5ce02-1ca1-11e8-839e-8b47b3a33b37.PNG)
As you can see the icons are still white on a white background. Also the links are underlined which is different from blocks that are not in the footer:
![unbenannt](https://user-images.githubusercontent.com/24255259/36795394-38e92e06-1ca3-11e8-815f-78aaec56e628.PNG)

**Comment by Kathrin84** [comment]
Hi,
thanks for the further feedback and the screenshots. I have to admit, that I oversaw the icons totally. So really thanks for the hint.
I also ignored the underlined context menu links, because Moodle now underlines links, nevertheless you are completely right on this issue.
So, I created another patch:
https://github.com/moodleuulm/moodle-theme_boost_campus/commit/8741426e9ee5dc401343b2c75f59539e167a97a7
It will be part of the next version v3.4-r4. ;)
I really hope that now everything is fine with the footer and the rest of the styling. :)
Best, Kathrin
