### ISSUE TITLE
Brand info color selection ignored

### ISSUE THREAD

**Issue by rolandsherwood2** [moodleuulm/moodle-theme_boost_campus#34]
Using version 2018052300 of the boost_campus theme under Moodle 3.5.1 stable, if a brand info color is selected by the user it is ignored and UI elements which previously (under version 2018020700 at least) respected the user selected color continue to be displayed using the default Boost color:

<img width="217" alt="screen shot 2018-07-24 at 14 54 37" src="https://user-images.githubusercontent.com/36252128/43121793-8b3ffae2-8f51-11e8-986e-7308e5211f04.png">
(version 2018020700 - user selected brand info color respected)

<img width="241" alt="screen shot 2018-07-24 at 14 59 30" src="https://user-images.githubusercontent.com/36252128/43122013-3716546a-8f52-11e8-9bfe-2d7a293f5334.png">
(version 2018052300 - user selected brand info color ignored)

**Comment by Kathrin84** [comment]
Hi @rolandsherwood2,

thank you for raising this issue. I did no recognize myself that this part was buggy since the latest release.

I did a fix: https://github.com/moodleuulm/moodle-theme_boost_campus/commit/14a4f6a71a6c7617e337cd6f28e2a73e9bd7d63a

This will be part of the next v3.5-r2 release coming in the nearer future.
As this bug is fixed, I'll close this issue.

Best, Kathrin

**Comment by rolandsherwood2** [comment]
Hi Kathrin,

Great! – and many thanks for providing a fix so quickly.

Best wishes,
Roland

Roland Sherwood
Manager
Educational Technologies Team
Educational Development Unit (ILEAD)
Xi’an Jiaotong-Liverpool University
Tel. 512-88161212
