### ISSUE TITLE
Blöcke rechts statt links (Blocks on the left side)

### ISSUE THREAD

**Issue by hermann-landolt** [moodleuulm/moodle-theme_boost_campus#36]
Für mich ist es hier der 1. Eintrag auf github! Ich hoffe, ich platziere hier mein Anliegen am richtigen Ort und darf es auch auf Deutsch machen?!
Bei mir erscheinen alle Blöcke auf der rechten Seite. Gibt es eine Möglichkeit, dass ich als Admin alle Blöcke standardmäßig auf die linke Seite platzieren kann? Oder finde ich diese Einstellungen gar nicht in den Designeinstellungen?

**Comment by Kathrin84** [comment]
Hello @hermann-landolt,

thank you for your issue. It is the right place. :)
We would appreciate if you could raise your issue in English, so everybody can understand you issue / question. Therefore I'll summarize it in English and answer you in English, too.

Q: hermann-landot asked if there's a possibility or a setting to place blocks on the left side in the course.

A: We use Boost core functionality here and did not do any changes to the block region within a course. So there's no setting in Boost core and neither in our theme.
We also do not consider adding such a setting because the slide-in navigation is placed on the left side and we think the content-first approach within the course is the most useful one.

But thank you very much for your question. I hope my answer did help you. 

Because there's nothing for us to remain done, I will close this issue.

Best, Kathrin
