### ISSUE TITLE
Option "Switch role to...": allow it to be in both places

### ISSUE THREAD

**Issue by lucaboesch** [moodleuulm/moodle-theme_boost_campus#38]
Dear Kathrin

I've got a feature request I'm also willing to work on.
The 'Move "Switch role to..." to the course settings' option allows to move the named option to the course settings. Or you could just leave it in the user menu as is.
Actually a third possibility is what I would think about: let it appear at both places!
So it gives usability in the course settings but also prevents puzzling questions from user which miss the function at the used place. 
I'd like to work on a pulldown menu labeled '"Switch role to..." location' (or similar) with the select options "just in the course settings / just in the user menu / in both places".
Of course with an upgrade script for transition from the actual theme to that upcoming version.

Best,
Luca

**Comment by Kathrin84** [comment]
Hi Luca,

thank you very much for your proposal.

I've got just another question to your user story:
Are there real usability reasons or user stories that the link needs to be placed in both places? Maybe because a teacher could not undo the changed role anymore or is it just a comfort aspect for users that do not like changes in the UI?

I'm not quite sure if I see the need for both places. Maybe it would be better to place it neither in the user menu nor in the course menu but maybe in another accessible place?

Maybe you can give me some more information to get the need a bit clearer.

Best, Kathrin

**Comment by lucaboesch** [comment]
Dear Kathrin
Yes, that is just comfort. For me, too!
Our institutions' theme is going to switch from a Clean based to a Boost Campus based (near the end of the year).
But I don't like the idea of having to explain hundreds of lecturers why the 'Switch to role…' option is not at the usual place any more. Allowing them to switch role in the course settings nevertheless, of course. So both places would be the classic "win-win".
I hope you see what I'm getting to.

Best,
Luca

**Comment by Kathrin84** [comment]
Hi Luca, 

I've took your code basis and added the changes I proposed to you within your patch regarding a new setting and the upgrade step.
Because of this, I could not apply your patch directly but I gave you credits in the CHANGES.md.

The change is now integrated into the master branch: https://github.com/moodleuulm/moodle-theme_boost_campus/commit/a7024d673421c858b45cd1817341048194e542fc

So, I'll close this issue.

Best, Kathrin
