### ISSUE TITLE
Move "footnote" from "Additional Layout Settings" to "Footer Layout Settings"

### ISSUE THREAD

**Issue by sennewood** [moodleuulm/moodle-theme_boost_campus#4]
The Footnote-Feature is placed under "Additional Layout Settings". I think it would be nicer to place it under "Footer Layout Settings". If you agree I will try to write a patch ;)

**Comment by Kathrin84** [comment]
Hi Sebastian,
thanks for your proposal!
Alex and I discussed the structure and had the following reason for this: We put it within the section "Additional Layout Settings" because it is an entirely additional area and is not part of the footer itself. For example, the footer block regions are inserted within the footer itself and so they belong to the "Footer Layout Settings" tab. The Footnote is not part of the footer, but a separate and additional area. So it does not belong to the footer settings.
I hope you understand the reason and I will close this issue without any changes to the theme.
Best, Kathrin
