### ISSUE TITLE
"My Courses" in the navigation bar instead of the menu item

### ISSUE THREAD

**Issue by hermann-landolt** [moodleuulm/moodle-theme_boost_campus#40]
Dear Kathrin
With some themes it is possible to add a drop down menu in the navigation bar with all my courses. Can I do this with Boost Campus? Where can I find these settings? Or what I have to enter in "custommenuitems"?

Best,
Hermann

**Comment by Kathrin84** [comment]
Hi @hermann-landolt,

thank you for your question. This is not possible with the theme Boost Campus, however with our plugin Boost Navigation Fumbling:
https://moodle.org/plugins/local_boostnavigation

Please have a look at that plugin. That should serve your needs.

Best, Kathrin

**Comment by hermann-landolt** [comment]
Dear Kathrin
Thank you for the quick answer. I know Boost Navigation Fumbling. But don't find the setting there.
Sorry, I didn't explain it very well. I want to move the root node "my courses" from the Boost's nav drawer to the header navbar.
![mycourses](https://user-images.githubusercontent.com/42239422/45101536-fc55ed80-b12b-11e8-89d1-59cebb140cab.JPG)

**Comment by Kathrin84** [comment]
Hi @hermann-landolt,
thank you for request and sorry for the late response.

I remember now that I wrote a comment with the hint to the plugin local_boostnavigationfumbling, but I deleted the comment as I did not read your request well enough and the first written answer was simply wrong. That's why I deleted it some moments after I submitted the comment. But you received the eMail notification. You cannot find any setting in local_boostnavigation to place the my courses node into the navbar.

This additional placement can technically be realized in the theme but currently there is no setting for this as we did not implement it and that's why you cannot find a setting in Boost Campus, too.

We also won't implement it in our theme for the following reasons:
* The list of courses can get really long (longer than the screen).
* This list would be duplicated in the boost navigation. 
(This _could_ be hidden with local_boostnavigation, but we cannot assume each instance will and can install this plugin , too.)
* We don't see any functional benefit in this feature as the course list will simply be duplicated.

Best, Kathrin
