### ISSUE TITLE
Problems with the helptextmodal function by using the forumng plugin

### ISSUE THREAD

**Issue by mwuttke** [moodleuulm/moodle-theme_boost_campus#41]
Hello Kathrin,

we are testing moodle 3.5.1+ (Build (2018051400) and your latest boost_campus theme (version 2018073100/release v3.5-r2) right now. We found an error by using the forumng plugin (version 2018011800) from the open university. It is not possible to activate the close button.

![bildschirmfoto vom 2018-09-06 18-28-49](https://user-images.githubusercontent.com/2102425/45171467-bfa8f580-b202-11e8-8a3b-a987a00d5060.png)

Please could you have a look at this issue.

I diabled the helptextmodal function for now.

Cheers,
Michael

**Comment by abias** [comment]
Hi Michael,

sorry for our late reply. We aren't using this forum plugin here, so we didn't encounter this flaw yet. Please give us some days to finish our 3.5 upgrade which has highest priority and we will then have a look at this issue.

Cheers,
Alex

**Comment by Kathrin84** [comment]
Hi @moodlebeuth,

unfortunately we really could not allocate any resources to deal with this issue until now as the priority for bugs with 3rd party plugins that we do not use ourself is very low and we don't see any chance in the nearer future to be able work on this.

Nevertheless, if you would provide a pull request, we can offer to review it. Otherwise we are closing this issue at this point.

We're sorry to write this but we hope for your understanding.

Best, Kathrin
