### ISSUE TITLE
body and HTML tags are closed before footer is output

### ISSUE THREAD

**Issue by digitalskill** [moodleuulm/moodle-theme_boost_campus#43]
The login.mustache template and columns2.mustache template have closing tags then the layouts call and render the additional footer items.

**Comment by digitalskill** [comment]
Hi Team,

Just following up on the update to see if the changes in the pull request are all good and if anything further is needed.

Cheers,

**Comment by Kathrin84** [comment]
Hi @digitalskill,

thank you for your issue and pull request.
Unfortunately we did not have time to have a look at this issue, yet. We will try to address it next week or in the nearer future.

Thank you for your patience and we'll come back to you.

Best, Kathrin

**Comment by digitalskill** [comment]
Just following up - Have you resolved that html is still being output after the closing </html> tags on pages

**Comment by Kathrin84** [comment]
Hi @digitalskill,

thank you very much for raising this issue and providing a patch. As the web inspectors do show the structure correctly and this bug was only visible if you had a look at the site source code, we were not aware of this bug.

Finally we found time to address this issue. We decided to go for another solution(https://github.com/moodleuulm/moodle-theme_boost_campus/commit/80a0d3c97762121c7b2e70ca8559fd17c62b592e) than you proposed with your pull request. Nevertheless your pull request is highly appreciated and thank you very much for the work you did with that!

The fix will be included in the next release of Boost Campus.

Best, Kathrin
