### ISSUE TITLE
cloze line break fix

### ISSUE THREAD

**Issue by sennewood** [moodleuulm/moodle-theme_boost_campus#5]
We experienced the following problem with a cloze (DE: Lückentext): at a small screen size the line break got triggered a lot:
![mdl_gaptext_pre](https://user-images.githubusercontent.com/406414/29119079-011d4702-7d05-11e7-903c-2926523cc238.png)

I fixed this with:

```css
p .subquestion {
   display: inline-block;
}
```

Now it looks like this:
![mdl_gaptext_post](https://user-images.githubusercontent.com/406414/29119117-28f7d4ae-7d05-11e7-81ba-8faef8d802c3.png)

**Comment by abias** [comment]
Hi Sebastian,

thanks for this issue.

At the very beginning of working on theme_boost_campus, we decided (internally) that we would not want to fix bugs of theme_boost in theme_boost_campus if there is a chance to have them solved in theme_boost directly. Otherwise, we would end up with a load of local fixes and overrides which wouldn't be manageable in the long run on the one hand and on the other hand the problem would only be solved for our child theme and not all Boost installations.

That's why I would want to ask you to check this:
* Is the problem you have encountered with the cloze questions also there in theme_boost on 3.2?
* If you have the chance to test the same thing on theme_boost on 3.3, is it gone there?

Thanks,
Alex

**Comment by sennewood** [comment]
It's from 3.3 and boost. Other test environments I don't have.

When it's not a theme issue, just close it :)

**Comment by abias** [comment]
Well, if this problem also does appear on theme_boost in Moodle core, I highly encourage you to report it on tracker.moodle.org to have it fixed globally. theme_boost_campus will then most probably inherit this fix from theme_boost.
