### ISSUE TITLE
Need to change the css classes for the additional course editing button

### ISSUE THREAD

**Issue by admin-teametry** [moodleuulm/moodle-theme_boost_campus#61]
Hi,

Where can I change/overwrite/add css classes for the course editing button? I tested a few things with renderers and so on, unfortunately without success. I want to use the bootstrap toggle feature:
https://gitbrent.github.io/bootstrap4-toggle/

Any hint is highly appreciated.

Thanks
Andreas

**Comment by Kathrin84** [comment]
Hi @admin-teametry,

thank you for your issue.

This is a nice idea, however first some thoughts why we would not implement this (even if you did not ask for this, it's just for the sake of completeness):
* We would need to add the additional jquery plugin as this is not shipped with Moodle itself.
* Toggle buttons are not widely used in Moodle and the users would probably not expect this button.

Regarding your question:
I can only say that we just override an core renderer and add the specific single button which was already used before boost: https://github.com/moodleuulm/moodle-theme_boost_campus/blob/master/classes/output/core_renderer.php#L76

On the fly I cannot tell you how you could easily change this to the required input fields with the necessary classes. I would try doing a Boost Campus child theme and writing a own mustache template for the button, call it in the overridden renderer function and don't forget to ship the jQuery plugin. 

I'm afraid beside this I cannot provide you more support because this would extent our resource capacities.

As we won't proceed here, I'll close this issue with this comment and thank you in advance for your understanding.

Best, Kathrin
