### ISSUE TITLE
add links to course settings dropdown menu

### ISSUE THREAD

**Issue by stemiwe** [moodleuulm/moodle-theme_boost_campus#70]
we added 2 links to the course settings dropdown, which make it easier for users to 

- delete a course
- directly access the question bank

(this setting only makes sense when not using boost_campus enhanced settings menu)

![coursenav](https://user-images.githubusercontent.com/13886080/70782724-fe274b80-1d87-11ea-8f7b-0a6361aef086.png)

if you want to include this change in boost_campus, i have the necessary code ready and can make a pull request

**Comment by lucaboesch** [comment]
A screenshot, maybe, Stefan?
Thanks for your suggestion!

**Comment by abias** [comment]
Hi @stemiwe  ,

many thanks for creating this issue which remained unhandled up to now, unfortunately.

As we have documented on https://moodle.org/plugins/theme_boost_campus, Boost Campus will not be continued after Moodle 3.x anymore as we will focus on the successor Boost Union which is published on https://moodle.org/plugins/theme_boost_union. For the time being, as long as Moodle 3.x still receives security support, we will only fix critical bugs in Boost Campus if one arises. And, of course, we try to port over all relevant features of Boost Campus and open proposals for Boost Campus to Boost Union.

Looking at your proposal from now, I think that there is now a fine direct link to the question bank in Moodle 4.x course navigation.
However, having a link to delete the course might be benefical in some setups and we could add an option to Boost Union to add this link.

Against this background, if you want to see this realized for Boost Union, please create an issue on https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues so that it can be discussed there.

Cheers,
Alex
