### ISSUE TITLE
edit icons instead of action menus on the course page

### ISSUE THREAD

**Issue by stemiwe** [moodleuulm/moodle-theme_boost_campus#71]
ever since MDL-55904 inexplicably decided to drop support for not hiding every action behind a dropdown menu, there is no way to bring back the edit icons in moodle, greatly decreasing usability

i think it would be a great feature to have in boost_campus, this is what it looks like at our site:

![editicons](https://user-images.githubusercontent.com/13886080/70711816-a2ef4d80-1ce2-11ea-8bfc-7d91e3ac3557.png)

our current integration is a little bit hacky, and consists both of css and php changes, and also requires changing code in plugins that add icons to the dropdown menu (eg sharing cart).

however, i'm sure a more elegant solution can be found. our current solution is:

in /course/lib.php:
- replace action_menu_link_secondary with -action_menu_link_primary
- delete block with /assign (assigning local roles is rarely used and can be accessed in the settings dropdown of an activity)
- change order of the other icon blocks

in /course/format/renderer.php:
- replace action_menu_link_secondary with -action_menu_link_primary
- in protected function section_edit_control_items move down the block `f (!$isstealth && has_capability('moodle/course:update', $coursecontext))`

in /course/format/topics/renderer.php:
delete the whole if block after `/* If the edit key exists, we are going to insert our controls after it.`

**Comment by abias** [comment]
Hi @stemiwe  ,

many thanks for creating this issue which remained unhandled up to now, unfortunately.

As we have documented on https://moodle.org/plugins/theme_boost_campus, Boost Campus will not be continued after Moodle 3.x anymore as we will focus on the successor Boost Union which is published on https://moodle.org/plugins/theme_boost_union. For the time being, as long as Moodle 3.x still receives security support, we will only fix critical bugs in Boost Campus if one arises. And, of course, we try to port over all relevant features of Boost Campus and open proposals for Boost Campus to Boost Union.

Regarding this proposal I have been torn ever since you created it. I see your point with the additional click to open the action menu, but I also see the benefit of a clean, uncluttered interface.

Against this background, if you want to see this realized for Boost Union, please create an issue on https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues so that it can be discussed there within a broader community.

Cheers,
Alex
