### ISSUE TITLE
fix logo sizes for moodle 3.7+

### ISSUE THREAD

**Issue by stemiwe** [moodleuulm/moodle-theme_boost_campus#72]
moodle 3.7 introduced a new way to render logos, which lead to some problems with bigger logos, see: https://moodle.org/mod/forum/discuss.php?d=388951

this can easily be reverted by including this in core_renderer.php, which returns to the old pre-3.7 behaviour:

  public function get_compact_logo_url($maxwidth = 100, $maxheight = 100) {
      return parent::get_compact_logo_url(null, 70);
  }

this would be super easy to implement and a nice-to-have

**Comment by Kathrin84** [comment]
Hi @stemiwe,

thank you very much for raising this issue and sorry for the really late response. COVID-19 pandemic mixed up a lot of things and made it impossible to deal with Boost Campus earlier.

I've seen that your issue has been fixed in Moodle core for Moodle 3.8+ (3.8.4):
https://tracker.moodle.org/browse/MDL-68270 

I know that you reported the issue for 3.7. However, even if we would have provided a patch it would have been integrated only into the 3.8 version of Boost Campus, too, because we are already on the 3.8 version and we do not provide patches for multiple versions.

So, as this is fixed in core I'll close this issue here.

Best, Kathrin
