### ISSUE TITLE
Errors in pre- or post- scss setting cause TDM to silently break 

### ISSUE THREAD

**Issue by frumbert** [moodleuulm/moodle-theme_boost_campus#80]
If you introduce a simple error into either the pre- or post- scss setting under advanced (e.g. `a { color: #56789;}` ), the theme compiler will [internally] throw an error and refuse to compile. This can lead to confusion - firstly purge caches won't reflect the styles added in the pre/post setting, and theme designer mode completely breaks resulting in no file at all being served via http://localhost/theme/styles_debug.php?theme=boost_campus&type=scss - not everybody knows to check their web servers php error log to find out why theme designer mode is breaking.

Would be be possible to run the pre- and post- scss settings through the scss compiler during form update to validate the contents and warn the user if the value isn't valid scss / css?

**Comment by Kathrin84** [comment]
Hi @frumbert,

thank you very much for raising this issue and sorry for the late reply. COVID-19 pandemic bounded all of resources to other urgent work within our institution.

There was a change in the setting some time ago we unfortunately missed... So your issue was very helpful to get this change. I changed the setting according theme Boost within this commit:
https://github.com/moodleuulm/moodle-theme_boost_campus/commit/1295067a8ce43bb62d49769d05595e8f1a68589c

With this change a validation will take place as it's implemented currently (does not work perfectly. Nevertheless it's better than nothing.)

This change will be part of the next release v3.8-r2.

I'll close this issue as fixed.

Best, Kathrin
