### ISSUE TITLE
Cutsomize footer size

### ISSUE THREAD

**Issue by grabs865** [moodleuulm/moodle-theme_boost_campus#82]
Hello,
on my project https://we-groosel.de I'd like to customize the hight of the footer on frontpage (what everyone can see before login). Where can I do this?
Regards!

**Comment by Kathrin84** [comment]
Hello @grabs865,

as my browser says that your website is not secure, I don't access your page and therefore I don't know how your page and footer looks like.
But I can say that the height of the footer is variable and dependent on the contents that lie within it and there is no setting for changing the height because it has no fixed height at all.

You could try to find a way with SCCS to realize what you intend to do. But I don't see a way that we would and could add a setting for this.

Best, Kathrin

**Comment by Kathrin84** [comment]
I'll close this issue at this point.
