### ISSUE TITLE
wrong file path for additionalresources ?

### ISSUE THREAD

**Issue by nicole-ll** [moodleuulm/moodle-theme_boost_campus#83]
In the setting "Add additional resources" (theme_boost_campus | additionalresources)
we uploaded an additional resource (impressum.html).
As described we referenced this resource by using the link  "/pluginfile.php/1/theme_boost_campus/additionalresources/0/impressum.html"
into "Additional HTML" Before BODY is closed additionalhtmlfooter.

If an unauthentified user clicks the link (works fine):
https://mymoodle.url/pluginfile.php/1/theme_boost_campus/additionalresources/0/impressum.html

If an authentified user clicks the link (whilst in a course) (error):
https://mymoodle.url/course/pluginfile.php/1/theme_boost_campus/additionalresources/0/impressum.html

How do we get rid of "course" ?

**Comment by Kathrin84** [comment]
Hi @nicole-ll,

thank you for raising this issue and sorry for the late response. COVID-19 pandemic mixed a lot of things up and delayed the work on this plugin.

Regarding your question:
I'm just serving the file from the specific file area by calling this function: https://github.com/moodleuulm/moodle-theme_boost_campus/blob/771fd2fe58a17f73e4fbd5b091b956d13e12a19f/lib.php#L182 which is defined here: https://github.com/moodle/moodle/blob/38abfb6a01888145878e7175e0431a156f6f1078/lib/outputlib.php#L1978
There the URL is built together and I don't do anything special within Boost Campus.
Especially you are using this file in another setting 'additionalhtmlfooter' that also does it's own magic.

We also described a use case for the setting 'additionalresources' and I don't think that your construct (espeacially with HTML files) should be done that way. If you want to present an imprint to users, we provide another plugin called "Static Pages" (https://moodle.org/plugins/local_staticpage) which does exactly what you intend to do. 
I would recommend that you have a glance at this plugin.

Because I don't see where I exactly could fix / improve Boost campus, there is a working solution for your use case and therefore it can be solved and I don't have the resources to invest more time in this issue I will close it at this point.

Thanks for your understanding and best, Kathrin.
