### ISSUE TITLE
Blocks can be added on edit section page

### ISSUE THREAD

**Issue by t-schroeder** [moodleuulm/moodle-theme_boost_campus#84]
We recently had a problem with https://github.com/unirz-tu-ilmenau/moodle-block_opencast

Each course has an instance of the block and _can_ only have one instance of the block. But one of our user managed to get around this restriction by doing this:

1. Go to course main page.
2. Turn editing on.
3. Next to the name of a topic/section click "Edit topic" or "Edit section".
4. Add the Opencast block.

The problem was then that backups for that course would always fail due to some endless recursion when comparing block settings between the two Opencast blocks. Therefore the user couldn't import content from his old course to the new one for the next semester.

What you end up with is two instances of an Opencast block with the only difference seemingly being the value for `pagetypepattern`:

- `course-view-*`
- `course-editsection`

The reason I'm creating an Issue for this theme and not for the Opencast block is that I can't replicate this with the default boost theme. There I simply can't add blocks on the editsection page, although there is and "Add block" button there. Is it intended that you are even able to add blocks on that page?

**Comment by abias** [comment]
Hi Tim,

due to Covid-19 lockdown and overwhelming work, our Boost Campus community work had to be paused. I just stumbled upon this issue as you cross-posted it on https://github.com/unirz-tu-ilmenau/moodle-block_opencast/issues/123.

As far as I remember, we just added a setting to move the "Add block" widget from the Boost nav drawer to the right page column. I think we did not change anything else to Block placements, but I may be wrong.

I think this problem should be solved on the consuming side (i.e. block_opencast) and I will comment there in a minute.

But I will leave this open here as well for further investigation.

Cheers,
Alex

**Comment by abias** [comment]
Hey Tim, 

while https://github.com/unirz-tu-ilmenau/moodle-block_opencast/issues/123 is still open, I think there is nothing we can do here in Boost Campus unless we understand what's really happening.

I dare to close this issue as we don't have time for this in-depth investigation.

Hope you understand.
Alex
