### ISSUE TITLE
Multiple background images result in a white page

### ISSUE THREAD

**Issue by sennewood** [moodleuulm/moodle-theme_boost_campus#9]
In the boost settings you can enable background images for the login page. One image works fine, but a secound image will always show as a white page.

**Comment by Kathrin84** [comment]
Hi Sebastian,
do you have some more detailed information for me? 
* What does your web inspector say? 
* Does the browser load the picture or does it error? 
* What type of image is the picture you uploaded to the setting? I restricted accepted types to
```'accepted_types' => 'web_image'```.
* How is the title of the file? No signs within that could cause problems within a URL?

Here is a picture how our setting looks like and it's working fine here:
![baxkground_images](https://user-images.githubusercontent.com/4711883/29703179-c2ad4946-8974-11e7-9eba-60f2b15f382b.png)
You can also send me your problem picture via mail and I can try to upload it to my system and have a look it it works here.
Cheers, Kathrin

**Comment by sennewood** [comment]
The upload isn't the problem :)

While testing with different pictures the error became a little bit stranger. After adding and deleting pictures (all .jpg), I right now have only one picture left I'm getting a blank background again:

![mdl_blank_bg](https://user-images.githubusercontent.com/406414/29706632-c43264c8-8982-11e7-9c4b-31e1d7ef3743.png)

I had to delete the moodle chache to fix this. So i don't think anymore that the issue are multiple pictures.

**Comment by Kathrin84** [comment]
Did you upload the same pictures with the same filenames again that you once had uploaded and deleted? Moodle keeps relations in the database. If you upload an image a second time, it will not be stored twice in the database. This is somehow clever, but while trying out and developing this might cause problems. I had similar issues with the badge area.
You could try to delete the pictures and upload them with a different filename and then purging the caches. I hope this will solve the problems you have.

And please have a look at the web inspector what it says regarding your image. There's a src-URL and you can have a look if this URL is correct or maybe if it's linking to an image that's not existing anymore (due to reasons I mentioned above).

**Comment by sennewood** [comment]
Interesting behavior ... well, that's explains it.
Thank you :)
