### ISSUE TITLE
Installation aborted due to validation failure (Moodle 3.9.1)

### ISSUE THREAD

**Issue by dcubedph** [moodleuulm/moodle-theme_boost_campus#98]
I get the following error when I tried installing it on a Moodle 3.9.1 installation:

Downloading theme_boost_campus ... OK
Validating theme_boost_campus ... Error
  [Error] Required Moodle version [2020061502] 
Installation aborted due to validation failure

![56362989-BE2B-41A6-9C88-CA0E161D64D6_4_5005_c](https://user-images.githubusercontent.com/5842300/95316302-345d2b00-08c6-11eb-9e60-8f09b61bc02c.jpeg)

**Comment by Kathrin84** [comment]
Hello @dcubedph,

the reason for this error is right in front of your eyes:
Required Moodle version [2020061502]

And this is the following version (https://docs.moodle.org/dev/Releases#Moodle_3.9_.28LTS.29):
Moodle 3.9.2 | 14 September 2020 | 2020061502 |

This is because of this commit:
https://github.com/moodleuulm/moodle-theme_boost_campus/commit/bcba3cf5ee1bbf9c5729f7639fb2ff858eba6bfc

So, please update your Moodle version accordingly and then the installation should work without errors.

As this is not a Boost Campus bug, I'll close this issue at this point.

Best, Kathrin
